# Generated by Django 4.2.16 on 2025-03-14 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mill', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlourBagCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bag_count', models.IntegerField()),
                ('bags_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timestamp', models.DateTimeField()),
                ('created_by', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device_id', models.CharField(default='web-interface', max_length=100)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flour_bag_counts', to='mill.batch')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['batch', 'timestamp'], name='mill_flourb_batch_i_d64632_idx')],
            },
        ),
    ]
