# Generated by Django 4.2.16 on 2024-10-18 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mill', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countersdata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='devicedata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
