# Generated by Django 4.2.16 on 2025-03-26 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mill', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='factory',
            name='group',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('commercial', 'Commercial')], default='public', max_length=30),
        ),
        migrations.CreateModel(
            name='FlourBagCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bag_count', models.IntegerField(default=0)),
                ('bags_weight', models.DecimalField(decimal_places=2, default=0.0, help_text='Total weight of bags in tons', max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flour_bag_counts', to='mill.batch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flour_bag_counts', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flour_bag_counts', to='mill.device')),
            ],
            options={
                'indexes': [models.Index(fields=['batch', 'device', 'timestamp'], name='mill_flourb_batch_i_4a018d_idx')],
            },
        ),
    ]
