# Generated by Django 4.2.16 on 2025-03-26 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mill', '0002_factory_group_flourbagcount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='factory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='mill.factory'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
