# Generated by Django 4.2.16 on 2025-01-13 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mill', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='id',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, unique=True),
        ),
    ]
