# Generated by Django 4.2.16 on 2025-01-27 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mill', '0003_alter_device_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='team',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
