# Generated by Django 4.2.16 on 2025-01-27 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mill', '0004_userprofile_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='team',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
