# Generated by Django 4.2.16 on 2025-04-07 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mill', '0004_notificationcategory_usernotificationpreference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='allowed_factories',
            field=models.ManyToManyField(blank=True, to='mill.factory'),
        ),
    ]
