# Generated by Django 4.2.16 on 2025-02-25 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mill', '0005_alter_userprofile_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchForFactory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batchInteger', models.IntegerField()),
                ('amountofwheat', models.IntegerField(default=0)),
                ('DateTimeField', models.DateTimeField(auto_now_add=True)),
                ('waistfactor', models.IntegerField(default=20)),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_for_factory', to='mill.factory')),
            ],
        ),
    ]
