# Generated by Django 4.2.16 on 2025-04-07 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mill', '0005_userprofile_allowed_factories'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('mobile_signal', models.IntegerField(blank=True, null=True)),
                ('dout_enabled', models.CharField(blank=True, max_length=255, null=True)),
                ('dout', models.CharField(blank=True, max_length=255, null=True)),
                ('di_mode', models.CharField(blank=True, max_length=255, null=True)),
                ('din', models.CharField(blank=True, max_length=255, null=True)),
                ('counter_1', models.IntegerField(blank=True, null=True)),
                ('counter_2', models.IntegerField(blank=True, null=True)),
                ('counter_3', models.IntegerField(blank=True, null=True)),
                ('counter_4', models.IntegerField(blank=True, null=True)),
                ('ain_mode', models.CharField(blank=True, max_length=255, null=True)),
                ('ain1_value', models.FloatField(blank=True, null=True)),
                ('ain2_value', models.FloatField(blank=True, null=True)),
                ('ain3_value', models.FloatField(blank=True, null=True)),
                ('ain4_value', models.FloatField(blank=True, null=True)),
                ('ain5_value', models.FloatField(blank=True, null=True)),
                ('ain6_value', models.FloatField(blank=True, null=True)),
                ('ain7_value', models.FloatField(blank=True, null=True)),
                ('ain8_value', models.FloatField(blank=True, null=True)),
                ('start_flag', models.IntegerField(blank=True, null=True)),
                ('type', models.IntegerField(blank=True, null=True)),
                ('length', models.IntegerField(blank=True, null=True)),
                ('version', models.IntegerField(blank=True, null=True)),
                ('end_flag', models.IntegerField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_data', to='mill.device')),
            ],
        ),
    ]
