# Generated by Django 4.2.16 on 2025-04-22 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mill', '0006_rawdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('ticket_type', models.CharField(choices=[('TECHNICAL', 'Technical Support'), ('ACCOUNT', 'Account Issues'), ('FEATURE', 'Feature Request'), ('BUG', 'Bug Report'), ('OTHER', 'Other Inquiry')], max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=10)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('IN_PROGRESS', 'In Progress'), ('PENDING', 'Pending User Response'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='NEW', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_tickets', to=settings.AUTH_USER_MODEL)),
                ('factory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mill.factory')),
            ],
            options={
                'verbose_name': 'Contact Ticket',
                'verbose_name_plural': 'Contact Tickets',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='mill_contac_status_97fb16_idx'), models.Index(fields=['ticket_type', 'status'], name='mill_contac_ticket__3b6c64_idx'), models.Index(fields=['created_by', 'status'], name='mill_contac_created_32acf1_idx'), models.Index(fields=['assigned_to', 'status'], name='mill_contac_assigne_9338b5_idx')],
            },
        ),
    ]
