# Generated by Django 4.2.16 on 2025-04-23 20:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mill', '0007_contactticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoorOpenLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('counter_id', models.IntegerField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='door_open_logs', to='mill.device')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='door_logs_resolved', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Door Open Log',
                'verbose_name_plural': 'Door Open Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
