# Generated by Django 4.2.16 on 2025-04-26 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mill', '0007_batch_status'),
        ('mill', '0008_dooropenlogs'),
    ]

    operations = [
    ]
