# Generated by Django 4.2.16 on 2025-06-01 14:12

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mill', '0009_merge_0007_batch_status_0008_dooropenlogs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='start_date',
            field=models.DateTimeField(default=timezone.now),  # Temporary default
        ),
        migrations.AlterField(
            model_name='batch',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True),  # Final field
        ),
    ]
