# Generated by Django 4.2.16 on 2025-06-01 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mill', '0010_alter_batch_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='start_value',
            field=models.IntegerField(default=0, help_text='Starting counter value from latest transaction'),
        ),
    ]
