# Generated by Django 4.2.16 on 2025-06-06 11:45

from django.db import migrations

def create_feedback_categories(apps, schema_editor):
    FeedbackCategory = apps.get_model('mill', 'FeedbackCategory')
    categories = [
        {
            'name': 'Data Discrepancy',
            'description': 'Report differences between expected and shown production values'
        },
        {
            'name': 'System Error',
            'description': 'Report technical issues or errors in the system'
        },
        {
            'name': 'Feature Request',
            'description': 'Suggest new features or improvements'
        },
        {
            'name': 'Other',
            'description': 'Other general feedback'
        },
    ]
    
    for category in categories:
        FeedbackCategory.objects.create(**category)

class Migration(migrations.Migration):

    dependencies = [
        ('mill', '0012_feedbackcategory_feedback'),
    ]

    operations = [
        migrations.RunPython(create_feedback_categories),
    ]
