# Generated by Django 4.2.16 on 2025-07-17 07:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mill', '0013_auto_20250606_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='batch',
            name='current_value',
            field=models.IntegerField(default=0, help_text='Current counter value'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('in_process', 'In Process'), ('paused', 'Paused'), ('stopped', 'Stopped'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='factory',
            name='group',
            field=models.CharField(choices=[('Public', 'Public'), ('private', 'Private'), ('commercial', 'Commercial')], default='Public', max_length=30),
        ),
        migrations.CreateModel(
            name='BatchNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('batch_created', 'Batch Created'), ('batch_approved', 'Batch Approved'), ('batch_started', 'Batch Started'), ('batch_paused', 'Batch Paused'), ('batch_completed', 'Batch Completed'), ('batch_rejected', 'Batch Rejected'), ('batch_100_percent', 'Batch 100% Complete')], max_length=20)),
                ('message', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('email_sent', models.BooleanField(default=False)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='mill.batch')),
                ('sent_to', models.ManyToManyField(related_name='batch_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
    ]
