# Generated by Django 4.2.16 on 2025-07-17 17:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mill', '0015_tvdashboardsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvdashboardsettings',
            name='accent_color',
            field=models.CharField(default='#FFD700', help_text='Accent color (hex code)', max_length=7),
        ),
        migrations.AddField(
            model_name='tvdashboardsettings',
            name='alert_duration',
            field=models.IntegerField(default=5000, help_text='Alert display duration in milliseconds', validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(30000)]),
        ),
        migrations.AddField(
            model_name='tvdashboardsettings',
            name='alert_position',
            field=models.CharField(choices=[('top-right', 'Top Right'), ('top-left', 'Top Left'), ('bottom-right', 'Bottom Right'), ('bottom-left', 'Bottom Left'), ('center', 'Center')], default='top-right', help_text='Position of alert notifications', max_length=20),
        ),
        migrations.AddField(
            model_name='tvdashboardsettings',
            name='animation_speed',
            field=models.CharField(choices=[('slow', 'Slow'), ('normal', 'Normal'), ('fast', 'Fast'), ('none', 'No Animation')], default='normal', help_text='Animation speed', max_length=10),
        ),
        migrations.AddField(
            model_name='tvdashboardsettings',
            name='background_color',
            field=models.CharField(default='#1e3c72', help_text='Background color (hex code)', max_length=7),
        ),
        migrations.AddField(
            model_name='tvdashboardsettings',
            name='background_image_url',
            field=models.URLField(blank=True, help_text='URL for background image', null=True),
        ),
        migrations.AddField(
            model_name='tvdashboardsettings',
            name='background_style',
            field=models.CharField(choices=[('gradient', 'Gradient Background'), ('solid', 'Solid Color'), ('pattern', 'Pattern Background'), ('image', 'Image Background'), ('animated', 'Animated Background')], default='gradient', help_text='Background style', max_length=20),
        ),
        migrations.AddField(
            model_name='tvdashboardsettings',
            name='card_border_radius',
            field=models.IntegerField(default=15, help_text='Card border radius in pixels', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AddField(
            model_name='tvdashboardsettings',
            name='card_border_width',
            field=models.IntegerField(default=1, help_text='Card border width in pixels', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='tvdashboardsettings',
            name='card_shadow',
            field=models.CharField(choices=[('none', 'No Shadow'), ('light', 'Light Shadow'), ('medium', 'Medium Shadow'), ('heavy', 'Heavy Shadow')], default='medium', help_text='Card shadow style', max_length=20),
        ),
        migrations.AddField(
            model_name='tvdashboardsettings',
            name='card_spacing',
            field=models.IntegerField(default=25, help_text='Spacing between cards in pixels', validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AddField(
            model_name='tvdashboardsettings',
            name='card_transparency',
            field=models.IntegerField(default=10, help_text='Card transparency percentage', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='tvdashboardsettings',
            name='color_theme',
            field=models.CharField(choices=[('default', 'Default Blue'), ('dark', 'Dark Theme'), ('light', 'Light Theme'), ('green', 'Green Theme'), ('purple', 'Purple Theme'), ('orange', 'Orange Theme'), ('red', 'Red Theme'), ('custom', 'Custom Colors')], default='default', help_text='Color theme for the dashboard', max_length=20),
        ),
        migrations.AddField(
            model_name='tvdashboardsettings',
            name='danger_color',
            field=models.CharField(default='#dc3545', help_text='Danger color (hex code)', max_length=7),
        ),
        migrations.AddField(
            model_name='tvdashboardsettings',
            name='font_family',
            field=models.CharField(choices=[('Arial', 'Arial'), ('Helvetica', 'Helvetica'), ('Times New Roman', 'Times New Roman'), ('Georgia', 'Georgia'), ('Verdana', 'Verdana'), ('Tahoma', 'Tahoma'), ('Trebuchet MS', 'Trebuchet MS'), ('Impact', 'Impact'), ('Comic Sans MS', 'Comic Sans MS')], default='Arial', help_text='Font family for text', max_length=50),
        ),
        migrations.AddField(
            model_name='tvdashboardsettings',
            name='font_size_base',
            field=models.IntegerField(default=16, help_text='Base font size in pixels', validators=[django.core.validators.MinValueValidator(12), django.core.validators.MaxValueValidator(24)]),
        ),
        migrations.AddField(
            model_name='tvdashboardsettings',
            name='font_size_large',
            field=models.IntegerField(default=20, help_text='Large font size in pixels', validators=[django.core.validators.MinValueValidator(16), django.core.validators.MaxValueValidator(32)]),
        ),
        migrations.AddField(
            model_name='tvdashboardsettings',
            name='font_size_xlarge',
            field=models.IntegerField(default=24, help_text='Extra large font size in pixels', validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(48)]),
        ),
        migrations.AddField(
            model_name='tvdashboardsettings',
            name='font_weight',
            field=models.CharField(choices=[('normal', 'Normal'), ('bold', 'Bold'), ('lighter', 'Lighter'), ('bolder', 'Bolder')], default='normal', help_text='Font weight', max_length=20),
        ),
        migrations.AddField(
            model_name='tvdashboardsettings',
            name='hover_effects',
            field=models.BooleanField(default=True, help_text='Enable hover effects on cards'),
        ),
        migrations.AddField(
            model_name='tvdashboardsettings',
            name='primary_color',
            field=models.CharField(default='#0d6efd', help_text='Primary color (hex code)', max_length=7),
        ),
        migrations.AddField(
            model_name='tvdashboardsettings',
            name='progress_animation',
            field=models.BooleanField(default=True, help_text='Animate progress bars'),
        ),
        migrations.AddField(
            model_name='tvdashboardsettings',
            name='progress_style',
            field=models.CharField(choices=[('linear', 'Linear Bar'), ('circular', 'Circular Progress'), ('steps', 'Step Indicator'), ('dots', 'Dot Progress')], default='linear', help_text='Style of progress indicators', max_length=20),
        ),
        migrations.AddField(
            model_name='tvdashboardsettings',
            name='secondary_color',
            field=models.CharField(default='#6c757d', help_text='Secondary color (hex code)', max_length=7),
        ),
        migrations.AddField(
            model_name='tvdashboardsettings',
            name='section_padding',
            field=models.IntegerField(default=20, help_text='Padding around sections in pixels', validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AddField(
            model_name='tvdashboardsettings',
            name='show_alerts',
            field=models.BooleanField(default=True, help_text='Show alert notifications'),
        ),
        migrations.AddField(
            model_name='tvdashboardsettings',
            name='show_progress_bars',
            field=models.BooleanField(default=True, help_text='Show progress bars for production data'),
        ),
        migrations.AddField(
            model_name='tvdashboardsettings',
            name='success_color',
            field=models.CharField(default='#198754', help_text='Success color (hex code)', max_length=7),
        ),
        migrations.AddField(
            model_name='tvdashboardsettings',
            name='transition_effects',
            field=models.BooleanField(default=True, help_text='Enable transition effects'),
        ),
        migrations.AddField(
            model_name='tvdashboardsettings',
            name='warning_color',
            field=models.CharField(default='#ffc107', help_text='Warning color (hex code)', max_length=7),
        ),
    ]
