# Generated by Django 4.2.16 on 2025-07-17 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mill', '0016_tvdashboardsettings_accent_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvdashboardsettings',
            name='show_alert_notifications',
            field=models.BooleanField(default=True, help_text='Show alert notifications and warnings'),
        ),
        migrations.AddField(
            model_name='tvdashboardsettings',
            name='show_batch_information',
            field=models.BooleanField(default=True, help_text='Show current batch information'),
        ),
        migrations.AddField(
            model_name='tvdashboardsettings',
            name='show_clock_display',
            field=models.BooleanField(default=True, help_text='Show current time and date display'),
        ),
        migrations.AddField(
            model_name='tvdashboardsettings',
            name='show_device_health',
            field=models.BooleanField(default=True, help_text='Show device health and status'),
        ),
        migrations.AddField(
            model_name='tvdashboardsettings',
            name='show_door_status',
            field=models.BooleanField(default=True, help_text='Show door open/close status'),
        ),
        migrations.AddField(
            model_name='tvdashboardsettings',
            name='show_efficiency_ratios',
            field=models.BooleanField(default=True, help_text='Show efficiency ratios and percentages'),
        ),
        migrations.AddField(
            model_name='tvdashboardsettings',
            name='show_energy_consumption',
            field=models.BooleanField(default=False, help_text='Show energy consumption data'),
        ),
        migrations.AddField(
            model_name='tvdashboardsettings',
            name='show_humidity_levels',
            field=models.BooleanField(default=False, help_text='Show humidity levels from sensors'),
        ),
        migrations.AddField(
            model_name='tvdashboardsettings',
            name='show_maintenance_alerts',
            field=models.BooleanField(default=True, help_text='Show maintenance alerts and reminders'),
        ),
        migrations.AddField(
            model_name='tvdashboardsettings',
            name='show_maintenance_status',
            field=models.BooleanField(default=True, help_text='Show maintenance status and schedules'),
        ),
        migrations.AddField(
            model_name='tvdashboardsettings',
            name='show_network_status',
            field=models.BooleanField(default=True, help_text='Show network connectivity status'),
        ),
        migrations.AddField(
            model_name='tvdashboardsettings',
            name='show_operator_info',
            field=models.BooleanField(default=False, help_text='Show current operator information'),
        ),
        migrations.AddField(
            model_name='tvdashboardsettings',
            name='show_performance_metrics',
            field=models.BooleanField(default=True, help_text='Show performance metrics and KPIs'),
        ),
        migrations.AddField(
            model_name='tvdashboardsettings',
            name='show_power_consumption',
            field=models.BooleanField(default=False, help_text='Show power consumption data'),
        ),
        migrations.AddField(
            model_name='tvdashboardsettings',
            name='show_pressure_readings',
            field=models.BooleanField(default=False, help_text='Show pressure readings from sensors'),
        ),
        migrations.AddField(
            model_name='tvdashboardsettings',
            name='show_production_alerts',
            field=models.BooleanField(default=True, help_text='Show production-related alerts'),
        ),
        migrations.AddField(
            model_name='tvdashboardsettings',
            name='show_production_charts',
            field=models.BooleanField(default=True, help_text='Show production charts and graphs'),
        ),
        migrations.AddField(
            model_name='tvdashboardsettings',
            name='show_production_targets',
            field=models.BooleanField(default=True, help_text='Show production targets and goals'),
        ),
        migrations.AddField(
            model_name='tvdashboardsettings',
            name='show_quality_alerts',
            field=models.BooleanField(default=True, help_text='Show quality control alerts'),
        ),
        migrations.AddField(
            model_name='tvdashboardsettings',
            name='show_quality_metrics',
            field=models.BooleanField(default=True, help_text='Show quality metrics and standards'),
        ),
        migrations.AddField(
            model_name='tvdashboardsettings',
            name='show_safety_alerts',
            field=models.BooleanField(default=True, help_text='Show safety alerts and warnings'),
        ),
        migrations.AddField(
            model_name='tvdashboardsettings',
            name='show_shift_information',
            field=models.BooleanField(default=False, help_text='Show shift information and schedules'),
        ),
        migrations.AddField(
            model_name='tvdashboardsettings',
            name='show_system_alerts',
            field=models.BooleanField(default=True, help_text='Show system and technical alerts'),
        ),
        migrations.AddField(
            model_name='tvdashboardsettings',
            name='show_system_status',
            field=models.BooleanField(default=True, help_text='Show system status and health indicators'),
        ),
        migrations.AddField(
            model_name='tvdashboardsettings',
            name='show_temperature_readings',
            field=models.BooleanField(default=False, help_text='Show temperature readings from sensors'),
        ),
        migrations.AddField(
            model_name='tvdashboardsettings',
            name='show_vibration_data',
            field=models.BooleanField(default=False, help_text='Show vibration data from sensors'),
        ),
        migrations.AddField(
            model_name='tvdashboardsettings',
            name='show_weather_info',
            field=models.BooleanField(default=False, help_text='Show weather information (if available)'),
        ),
    ]
