# Generated by Django 4.2.16 on 2025-07-17 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mill', '0017_tvdashboardsettings_show_alert_notifications_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factory',
            name='address',
            field=models.TextField(blank=True, help_text='Full address of the factory', null=True),
        ),
        migrations.AddField(
            model_name='factory',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude coordinate', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='factory',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude coordinate', max_digits=9, null=True),
        ),
    ]
