# Generated by Django 4.2.16 on 2025-07-18 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mill', '0020_emailtemplate_template_type_emailtemplate_variables_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='microsoft365settings',
            name='auth_user',
            field=models.EmailField(default='Defoult title', help_text='Email address of the user account to use for authentication (e.g., admin@company.com)', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='microsoft365settings',
            name='from_email',
            field=models.EmailField(help_text='Email address that will appear as sender (can be shared mailbox like shared@company.com)', max_length=254),
        ),
    ]
