# Generated by Django 4.2.16 on 2025-07-19 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mill', '0021_add_auth_user_to_microsoft365settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='microsoft365settings',
            name='redirect_uri',
        ),
        migrations.RemoveField(
            model_name='microsoft365settings',
            name='smtp_port',
        ),
        migrations.RemoveField(
            model_name='microsoft365settings',
            name='smtp_server',
        ),
        migrations.RemoveField(
            model_name='microsoft365settings',
            name='use_tls',
        ),
        migrations.AlterField(
            model_name='microsoft365settings',
            name='access_token',
            field=models.TextField(blank=True, default='not set', help_text='OAuth2 access token'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='microsoft365settings',
            name='auth_user',
            field=models.CharField(blank=True, help_text='User email for authentication (e.g., danny.v@...)', max_length=255),
        ),
        migrations.AlterField(
            model_name='microsoft365settings',
            name='client_id',
            field=models.CharField(blank=True, help_text='Azure AD Application Client ID', max_length=255),
        ),
        migrations.AlterField(
            model_name='microsoft365settings',
            name='client_secret',
            field=models.CharField(blank=True, help_text='Azure AD Application Client Secret', max_length=255),
        ),
        migrations.AlterField(
            model_name='microsoft365settings',
            name='from_email',
            field=models.CharField(blank=True, help_text='Shared mailbox email (e.g., noreply@...)', max_length=255),
        ),
        migrations.AlterField(
            model_name='microsoft365settings',
            name='from_name',
            field=models.CharField(default='Mill Application', help_text='From name for emails', max_length=255),
        ),
        migrations.AlterField(
            model_name='microsoft365settings',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Active configuration'),
        ),
        migrations.AlterField(
            model_name='microsoft365settings',
            name='refresh_token',
            field=models.TextField(blank=True, default='not set', help_text='OAuth2 refresh token'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='microsoft365settings',
            name='tenant_id',
            field=models.CharField(blank=True, help_text='Azure AD Tenant ID', max_length=255),
        ),
        migrations.AlterField(
            model_name='microsoft365settings',
            name='token_expires_at',
            field=models.DateTimeField(blank=True, help_text='Token expiration time', null=True),
        ),
        migrations.CreateModel(
            name='TicketResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_internal', models.BooleanField(default=False, help_text='Internal note not visible to user')),
                ('is_read', models.BooleanField(default=False, help_text='Whether the response has been read')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_responses', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='mill.contactticket')),
            ],
            options={
                'verbose_name': 'Ticket Response',
                'verbose_name_plural': 'Ticket Responses',
                'ordering': ['created_at'],
            },
        ),
    ]
