# Generated by Django 4.2.16 on 2025-07-19 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mill', '0022_remove_microsoft365settings_redirect_uri_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='support_tickets_enabled',
            field=models.BooleanField(default=False, help_text='Enable support tickets management for this user'),
        ),
    ]
