# Generated by Django 4.2.16 on 2025-07-22 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mill', '0023_userprofile_support_tickets_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='preferred_layout',
            field=models.CharField(choices=[('modern', 'Modern Layout'), ('classic', 'Classic Layout')], default='modern', help_text="User's preferred layout style", max_length=10),
        ),
    ]
