# Generated by Django 4.2.16 on 2025-07-22 22:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mill', '0026_powernotificationsettings_powerevent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PowerManagementPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_access_power_management', models.BooleanField(default=False)),
                ('can_view_power_status', models.BooleanField(default=False)),
                ('can_resolve_power_events', models.BooleanField(default=False)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='power_permissions_granted', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='power_management_permission', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Power Management Permission',
                'verbose_name_plural': 'Power Management Permissions',
            },
        ),
    ]
