# Generated by Django 4.2.16 on 2025-07-24 08:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mill', '0027_powermanagementpermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='factory',
            name='responsible_users',
            field=models.ManyToManyField(blank=True, help_text='Users responsible for this factory (will receive notifications)', related_name='responsible_factories', to=settings.AUTH_USER_MODEL),
        ),
    ]
