# Generated by Django 4.2.16 on 2025-07-24 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mill', '0028_factory_responsible_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawdata',
            name='digital_input_1',
            field=models.BooleanField(blank=True, help_text='Digital Input 1', null=True),
        ),
        migrations.AddField(
            model_name='rawdata',
            name='digital_input_2',
            field=models.BooleanField(blank=True, help_text='Digital Input 2', null=True),
        ),
        migrations.AddField(
            model_name='rawdata',
            name='digital_input_3',
            field=models.BooleanField(blank=True, help_text='Digital Input 3', null=True),
        ),
        migrations.AddField(
            model_name='rawdata',
            name='digital_input_4',
            field=models.BooleanField(blank=True, help_text='Digital Input 4 (Door Status)', null=True),
        ),
        migrations.AddField(
            model_name='rawdata',
            name='digital_output_1',
            field=models.BooleanField(blank=True, help_text='Digital Output 1', null=True),
        ),
        migrations.AddField(
            model_name='rawdata',
            name='digital_output_2',
            field=models.BooleanField(blank=True, help_text='Digital Output 2', null=True),
        ),
        migrations.AddField(
            model_name='rawdata',
            name='digital_output_3',
            field=models.BooleanField(blank=True, help_text='Digital Output 3', null=True),
        ),
        migrations.AddField(
            model_name='rawdata',
            name='digital_output_4',
            field=models.BooleanField(blank=True, help_text='Digital Output 4', null=True),
        ),
    ]
