# Generated by Django 4.2.16 on 2025-07-24 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mill', '0028_factory_responsible_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawdata',
            name='type',
        ),
        migrations.AddField(
            model_name='device',
            name='serial_number',
            field=models.CharField(blank=True, help_text='Device serial number', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rawdata',
            name='data_type',
            field=models.IntegerField(blank=True, help_text='Data type identifier', null=True),
        ),
    ]
