# Generated by Django 4.2.16 on 2025-07-24 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mill', '0029_remove_rawdata_type_device_serial_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoorStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_open', models.BooleanField(default=False)),
                ('last_din_data', models.CharField(blank=True, help_text='Last din array data', max_length=255, null=True)),
                ('last_check', models.DateTimeField(auto_now=True)),
                ('door_input_index', models.IntegerField(default=3, help_text='Index in din array for door status (0-3)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Door Status',
                'verbose_name_plural': 'Door Statuses',
            },
        ),
        migrations.RemoveField(
            model_name='dooropenlogs',
            name='counter_id',
        ),
        migrations.AddField(
            model_name='dooropenlogs',
            name='din_data',
            field=models.CharField(blank=True, help_text='din array data when door opened', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dooropenlogs',
            name='door_input_index',
            field=models.IntegerField(default=3, help_text='Index in din array for door status'),
        ),
        migrations.AddIndex(
            model_name='dooropenlogs',
            index=models.Index(fields=['device', 'timestamp'], name='mill_doorop_device__318e49_idx'),
        ),
        migrations.AddIndex(
            model_name='dooropenlogs',
            index=models.Index(fields=['is_resolved'], name='mill_doorop_is_reso_b8cdbb_idx'),
        ),
        migrations.AddField(
            model_name='doorstatus',
            name='device',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='door_status', to='mill.device'),
        ),
        migrations.AddIndex(
            model_name='doorstatus',
            index=models.Index(fields=['device', 'is_open'], name='mill_doorst_device__4a5ffc_idx'),
        ),
        migrations.AddIndex(
            model_name='doorstatus',
            index=models.Index(fields=['last_check'], name='mill_doorst_last_ch_23c068_idx'),
        ),
    ]
