# Generated by Django 4.2.16 on 2025-07-24 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mill', '0030_doorstatus_remove_dooropenlogs_counter_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PowerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ain1_value', models.FloatField(blank=True, help_text='Power value from AIN1', null=True)),
                ('ain2_value', models.FloatField(blank=True, help_text='Power value from AIN2', null=True)),
                ('ain3_value', models.FloatField(blank=True, help_text='Power value from AIN3', null=True)),
                ('ain4_value', models.FloatField(blank=True, help_text='Power value from AIN4', null=True)),
                ('has_power', models.BooleanField(default=True, help_text='Whether device has power')),
                ('power_threshold', models.FloatField(default=0.0, help_text='Power threshold for detection')),
                ('power_loss_count_today', models.IntegerField(default=0, help_text='Number of power losses today')),
                ('power_restore_count_today', models.IntegerField(default=0, help_text='Number of power restores today')),
                ('total_power_loss_time_today', models.DurationField(blank=True, help_text='Total time without power today', null=True)),
                ('power_loss_count_week', models.IntegerField(default=0, help_text='Number of power losses this week')),
                ('power_restore_count_week', models.IntegerField(default=0, help_text='Number of power restores this week')),
                ('total_power_loss_time_week', models.DurationField(blank=True, help_text='Total time without power this week', null=True)),
                ('power_loss_count_month', models.IntegerField(default=0, help_text='Number of power losses this month')),
                ('power_restore_count_month', models.IntegerField(default=0, help_text='Number of power restores this month')),
                ('total_power_loss_time_month', models.DurationField(blank=True, help_text='Total time without power this month', null=True)),
                ('power_loss_count_year', models.IntegerField(default=0, help_text='Number of power losses this year')),
                ('power_restore_count_year', models.IntegerField(default=0, help_text='Number of power restores this year')),
                ('total_power_loss_time_year', models.DurationField(blank=True, help_text='Total time without power this year', null=True)),
                ('avg_power_consumption_today', models.FloatField(default=0.0, help_text='Average power consumption today')),
                ('peak_power_consumption_today', models.FloatField(default=0.0, help_text='Peak power consumption today')),
                ('total_power_consumption_today', models.FloatField(default=0.0, help_text='Total power consumption today')),
                ('last_power_loss', models.DateTimeField(blank=True, help_text='Last time power was lost', null=True)),
                ('last_power_restore', models.DateTimeField(blank=True, help_text='Last time power was restored', null=True)),
                ('last_mqtt_update', models.DateTimeField(auto_now=True, help_text='Last MQTT data update')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='power_data', to='mill.device')),
            ],
            options={
                'verbose_name': 'Power Data',
                'verbose_name_plural': 'Power Data',
                'ordering': ['-last_mqtt_update'],
                'indexes': [models.Index(fields=['device', 'created_at'], name='mill_powerd_device__0518b7_idx'), models.Index(fields=['device', 'has_power'], name='mill_powerd_device__0e6f14_idx'), models.Index(fields=['last_mqtt_update'], name='mill_powerd_last_mq_2007bd_idx')],
            },
        ),
    ]
