# Generated by Django 4.2.16 on 2025-07-29 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mill', '0031_powerdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawDataCounter',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('counter_id', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('mobile_signal', models.IntegerField(blank=True, null=True)),
                ('dout_enabled', models.CharField(blank=True, max_length=50, null=True)),
                ('dout', models.CharField(blank=True, max_length=50, null=True)),
                ('di_mode', models.CharField(blank=True, max_length=50, null=True)),
                ('din', models.CharField(blank=True, max_length=50, null=True)),
                ('counter_1', models.IntegerField(blank=True, null=True)),
                ('counter_2', models.IntegerField(blank=True, null=True)),
                ('counter_3', models.IntegerField(blank=True, null=True)),
                ('counter_4', models.IntegerField(blank=True, null=True)),
                ('ain_mode', models.CharField(blank=True, max_length=50, null=True)),
                ('ain1_value', models.FloatField(blank=True, null=True)),
                ('ain2_value', models.FloatField(blank=True, null=True)),
                ('ain3_value', models.FloatField(blank=True, null=True)),
                ('ain4_value', models.FloatField(blank=True, null=True)),
                ('ain5_value', models.FloatField(blank=True, null=True)),
                ('ain6_value', models.FloatField(blank=True, null=True)),
                ('ain7_value', models.FloatField(blank=True, null=True)),
                ('ain8_value', models.FloatField(blank=True, null=True)),
                ('start_flag', models.IntegerField(blank=True, null=True)),
                ('type', models.IntegerField(blank=True, null=True)),
                ('length', models.IntegerField(blank=True, null=True)),
                ('version', models.IntegerField(blank=True, null=True)),
                ('end_flag', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'raw_data',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='factory',
            name='group',
            field=models.CharField(choices=[('government', 'Government'), ('private', 'Private'), ('commercial', 'Commercial')], default='government', max_length=30),
        ),
    ]
