# Generated by Django 4.2.16 on 2025-07-29 11:38

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mill', '0032_rawdatacounter_alter_factory_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('wheat_amount', models.DecimalField(decimal_places=2, help_text='Standard wheat amount in tons', max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('waste_factor', models.DecimalField(decimal_places=2, default=20.0, help_text='Standard waste factor percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('expected_duration_days', models.IntegerField(default=30, help_text='Expected batch duration in days', validators=[django.core.validators.MinValueValidator(1)])),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False, help_text='Default template for new batches')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicable_factories', models.ManyToManyField(blank=True, help_text='Factories where this template can be used', related_name='batch_templates', to='mill.factory')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_batch_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Batch Template',
                'verbose_name_plural': 'Batch Templates',
                'ordering': ['-is_default', 'name'],
            },
        ),
    ]
