# Generated by Django 4.2.16 on 2025-07-30 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mill', '0034_uc300pilotstatus_counterresetlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uc300pilotstatus',
            name='daily_reset_time',
            field=models.TimeField(blank=True, help_text='Daily reset time (e.g., 23:59)', null=True),
        ),
        migrations.CreateModel(
            name='UC300BatchStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_name', models.CharField(help_text='Name/ID of the batch', max_length=100)),
                ('batch_start_time', models.DateTimeField(help_text='When batch started')),
                ('batch_end_time', models.DateTimeField(blank=True, help_text='When batch ended', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether batch is currently active')),
                ('start_counter_value', models.IntegerField(blank=True, help_text='Counter value when batch started', null=True)),
                ('end_counter_value', models.IntegerField(blank=True, help_text='Counter value when batch ended', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Batch notes', null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_status', to='mill.device')),
            ],
            options={
                'ordering': ['-batch_start_time'],
                'indexes': [models.Index(fields=['device', 'is_active'], name='mill_uc300b_device__46d909_idx'), models.Index(fields=['is_active'], name='mill_uc300b_is_acti_b034df_idx'), models.Index(fields=['batch_start_time'], name='mill_uc300b_batch_s_1a5b2b_idx')],
            },
        ),
    ]
