# Generated by Django 4.2.16 on 2025-07-30 20:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mill', '0035_alter_uc300pilotstatus_daily_reset_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factory',
            name='uc300_pilot_enabled',
            field=models.BooleanField(default=False, help_text='Enable UC300 pilot project for this factory. This allows devices in this factory to participate in the UC300 reset system.'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='batch_management_enabled',
            field=models.BooleanField(default=False, help_text='Enable batch management for this user'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_approve_batches',
            field=models.BooleanField(default=False, help_text='Can approve batches'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_create_batches',
            field=models.BooleanField(default=False, help_text='Can create new batches'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_start_batches',
            field=models.BooleanField(default=False, help_text='Can start batches'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_stop_batches',
            field=models.BooleanField(default=False, help_text='Can stop batches'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_view_analytics',
            field=models.BooleanField(default=False, help_text='Can view batch analytics'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Batch start date - can be edited by super admin to include historical data'),
        ),
    ]
