name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: SSH Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_IP }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SECRET_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          script: |
            # Create the directory if it doesn't exist
            mkdir -p /home/administrator/project-mill-application
            cd /home/administrator/project-mill-application
            
            # Check if this is the first deployment
            if [ ! -d .git ]; then
              git clone https://github.com/Jjustmee23/mill-management-system.git .
            else
              git pull origin main
            fi
            
            
            ping -c 4 pypi.org

            # Stop and remove all running containers if any
            docker-compose down 
            
            # Remove the specific microservice container image if it exists
            
            # Build and start the containers
            docker-compose up -d postgres
            docker-compose up -d --build --remove-orphans
